[[constraint]]
  branch = "master"
  name = "github.com/rjeczalik/notify"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.2.1"

[[constraint]]
  branch = "master"
  name = "github.com/GeertJohan/go.rice"
