name: build
on: [push]

jobs:
  build:
    name: build

    permissions:
      packages: write

    uses: evanpurkhiser/workflows/docker.yml@main
    with:
      publish: ${{ github.ref == 'refs/heads/main' }}
