name: build
on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: docker build --tag=evanpurkhiser/waitress:latest .
      - name: Publish
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker login --username=evanpurkhiser --password-stdin <<< "${{ secrets.DOCKER_HUB_TOKEN }}"
          docker push evanpurkhiser/waitress:latest
