name: build
on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: docker build --tag=evanpurkhiser/waitress:latest .
      - name: GHCR Authenticate
        uses: docker/login-action@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        if: ${{ github.ref == 'refs/heads/main' }}
        run: docker push evanpurkhiser/waitress:latest
