name: build
on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: evanpurkhiser/workflows/docker.yml
